---
name: build-push

on:
  pull_request:
  push:
    paths:
      - 'alpine/latest/**'
      - '.github/workflows/build-and-push.yml'
  schedule:
    - cron: '20 */2 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: 'false'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: make build

      - name: Test building image.
        run: cd alpine/latest && docker build -t docker-curl .

      - name: Run the built image.
        run: docker run --name test-curl -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-curl

      - name: Verify Curl is accessible in the built image.
        run: curl --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: alpine/latest/
          file: alpine/latest/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:1.0.0, ${{ github.repository }}:latest
